'use client';

import * as React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, ArrowLeft, Car, Bike, Sparkles, Check, 
  Calendar, Clock, CreditCard, ChevronRight, AlertCircle 
} from 'lucide-react';
import { 
  useAppStore, ServiceCenter, WashService 
} from '@/lib/store';

interface BookingModalProps {
  center: ServiceCenter;
  isOpen: boolean;
  onClose: () => void;
}

export default function BookingModal({ center, isOpen, onClose }: BookingModalProps) {
  const { addBooking, isOffline, washServices, washSlots, vehicles } = useAppStore();
  const [step, setStep] = React.useState<number>(1);
  const [selectedVehicleId, setSelectedVehicleId] = React.useState<string>('');
  const [selectedService, setSelectedService] = React.useState<WashService>(() => washServices[0] || {
    id: 'ws-1',
    name: 'Express Hydro-Spritz',
    description: 'High-pressure filtered rinse, bio-soap scrub, micro-fiber high velocity air-dry & dust wiping.',
    duration: 25,
    priceCar: 25,
    priceBike: 15
  });
  const [selectedDate, setSelectedDate] = React.useState<string>(() => {
    if (typeof window !== 'undefined') {
      return new Date().toISOString().split('T')[0];
    }
    return '';
  });
  const [selectedSlot, setSelectedSlot] = React.useState<string>('10:00 AM - 11:00 AM');

  // Sync state if washServices updates
  React.useEffect(() => {
    if (washServices && washServices.length > 0) {
      setSelectedService(washServices[0]);
    }
    if (vehicles.length > 0 && !selectedVehicleId) {
      setSelectedVehicleId(vehicles[0].id);
    }
  }, [washServices, vehicles, selectedVehicleId]);

  if (!isOpen) return null;

  const selectedVehicle = vehicles.find(v => v.id === selectedVehicleId);
  const vehicleType = selectedVehicle?.type || 'car';

  // Pricing helper
  const getPrice = (service: WashService) => {
    return vehicleType === 'car' ? service.priceCar : service.priceBike;
  };

  const total = getPrice(selectedService); // This is inclusive total
  const basePrice = Number((total / 1.18).toFixed(2));
  const tax = Number((total - basePrice).toFixed(2));

  const handleNext = () => {
    if (step < 4) {
      setStep(step + 1);
    } else {
      // Confirm Booking
      addBooking({
        serviceCenterId: center.id,
        vehicleType,
        vehicleModel: selectedVehicle ? `${selectedVehicle.model} (${selectedVehicle.paint})` : 'Unknown Vehicle',
        serviceId: selectedService.id,
        date: selectedDate,
        timeSlot: selectedSlot,
        price: total
      });
      setStep(5);
    }
  };

  const handleBack = () => {
    if (step > 1) {
      setStep(step - 1);
    }
  };

  const daysAhead = [0, 1, 2, 3].map(offset => {
    const d = new Date();
    d.setDate(d.getDate() + offset);
    return {
      iso: d.toISOString().split('T')[0],
      dayName: offset === 0 ? 'Today' : d.toLocaleDateString('en-US', { weekday: 'short' }),
      num: d.getDate(),
      month: d.toLocaleDateString('en-US', { month: 'short' })
    };
  });

  const slotsAvailable = React.useMemo(() => {
    const centerSlotsForDate = washSlots.filter(
      s => s.serviceCenterId === center.id && s.date === selectedDate && !s.isBooked
    );
    if (centerSlotsForDate.length > 0) {
      return centerSlotsForDate.map(s => s.timeSlot);
    }
    // Fallback if no specific slots are generated by the admin yet
    return [
      '08:00 AM - 09:00 AM',
      '10:00 AM - 11:00 AM',
      '12:30 PM - 01:30 PM',
      '02:30 PM - 03:30 PM',
      '04:30 PM - 05:30 PM',
      '06:00 PM - 07:00 PM'
    ];
  }, [washSlots, center.id, selectedDate]);

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          transition={{ duration: 0.2 }}
          className="relative w-full max-w-lg bg-white rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
          id="booking-modal-outer"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-5 border-b border-gray-100 bg-gradient-to-r from-gray-50 to-white">
            <div className="flex items-center gap-2">
              {step > 1 && step < 5 && (
                <button 
                  onClick={handleBack} 
                  className="p-1 text-gray-500 hover:bg-gray-100 rounded-full transition-colors"
                  aria-label="Back"
                >
                  <ArrowLeft className="w-5 h-5" />
                </button>
              )}
              <div>
                <h3 className="font-semibold text-gray-900 text-lg">
                  {step === 5 ? 'Booking Confirmed' : `Book slot at ${center.name}`}
                </h3>
                {step < 5 && (
                  <p className="text-gray-400 text-xs font-medium">Step {step} of 4</p>
                )}
              </div>
            </div>
            
            <button 
              onClick={onClose} 
              className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
              aria-label="Close"
              id="close-booking-modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Progress Pill indicator */}
          {step < 5 && (
            <div className="w-full bg-gray-100 h-1">
              <motion.div 
                className="bg-blue-600 h-full" 
                initial={{ width: '25%' }}
                animate={{ width: `${step * 25}%` }}
                transition={{ duration: 0.3 }}
              />
            </div>
          )}

          {/* Content Area */}
          <div className="flex-1 overflow-y-auto p-5 space-y-5">
            {/* Offline notification banner inside modal */}
            {isOffline && step < 5 && (
              <div className="flex items-start gap-2.5 bg-amber-50 border border-amber-200 p-3.5 rounded-2xl">
                <AlertCircle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5 animate-pulse" />
                <div>
                  <p className="text-xs font-semibold text-amber-800">Booking Offline Queue Mode</p>
                  <p className="text-[11px] text-amber-600 mt-0.5 leading-relaxed">
                    You are currently offline. Your reservation will be securely cached locally, and fully uploaded immediately once network access is resumed!
                  </p>
                </div>
              </div>
            )}

            {/* STEP 1: Vehicle selection */}
            {step === 1 && (
              <div className="space-y-4" id="step-1-vehicle">
                <div>
                  <label className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Select Registered Vehicle</label>
                  {vehicles.length === 0 ? (
                    <p className="text-sm text-gray-500 p-4 border border-dashed rounded-2xl">No vehicles registered yet. Please add a vehicle in your profile dashboard.</p>
                  ) : (
                    <div className="grid grid-cols-1 gap-3">
                      {vehicles.map(v => (
                        <button
                          key={v.id}
                          type="button"
                          onClick={() => setSelectedVehicleId(v.id)}
                          className={`flex items-center gap-4 p-4 border rounded-2xl transition-all ${
                            selectedVehicleId === v.id
                              ? 'border-blue-600 bg-blue-50/50 text-blue-900 shadow-xs'
                              : 'border-gray-200 text-gray-600 hover:border-gray-300'
                          }`}
                        >
                          <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${v.type === 'car' ? 'bg-blue-100 text-blue-700' : 'bg-teal-100 text-teal-700'}`}>
                            {v.type === 'car' ? <Car className="w-5 h-5" /> : <Bike className="w-5 h-5" />}
                          </div>
                          <div className="text-left">
                            <p className="text-sm font-bold">{v.model}</p>
                            <p className="text-xs text-gray-500">{v.paint}</p>
                          </div>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* STEP 2: Service Wash selection */}
            {step === 2 && (
              <div className="space-y-3" id="step-2-service">
                <label className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Select Wash Tier</label>
                <div className="space-y-3">
                  {washServices.map((srv) => {
                    const price = getPrice(srv);
                    const isSelected = selectedService.id === srv.id;
                    return (
                      <button
                        key={srv.id}
                        type="button"
                        onClick={() => setSelectedService(srv)}
                        className={`w-full text-left p-4.5 border rounded-2xl flex items-start justify-between gap-3 transition-all ${
                          isSelected 
                            ? 'border-blue-600 bg-blue-50/30 ring-1 ring-blue-600 shadow-xs' 
                            : 'border-gray-100 hover:border-gray-200 hover:bg-gray-50/50'
                        }`}
                      >
                        <div className="space-y-1">
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-gray-800 text-sm">{srv.name}</span>
                            {srv.id === 'ws-2' && (
                              <span className="bg-emerald-50 text-emerald-700 text-[10px] font-bold px-1.5 py-0.5 rounded-md">Best Seller</span>
                            )}
                          </div>
                          <p className="text-[11px] text-gray-400 leading-relaxed font-normal">{srv.description}</p>
                          <div className="flex items-center gap-3 text-[11px] text-gray-500 font-medium pt-1.5">
                            <span className="flex items-center gap-1">⏱️ {srv.duration} mins</span>
                            <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
                            <span className="text-indigo-600">Premium active agent foam</span>
                          </div>
                        </div>
                        <div className="text-right shrink-0">
                          <span className="text-lg font-black text-gray-900">₹{price}</span>
                          <span className="text-[10px] block text-gray-400">Fixed rate</span>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* STEP 3: Scheduling */}
            {step === 3 && (
              <div className="space-y-5" id="step-3-schedule">
                <div className="space-y-2">
                  <label className="block text-xs font-bold text-gray-400 uppercase tracking-wider">Select Date</label>
                  <div className="grid grid-cols-4 gap-2">
                    {daysAhead.map((day) => {
                      const isSelected = selectedDate === day.iso;
                      return (
                        <button
                          key={day.iso}
                          type="button"
                          onClick={() => setSelectedDate(day.iso)}
                          className={`flex flex-col items-center p-3 border rounded-xl transition-all ${
                            isSelected 
                              ? 'border-blue-600 bg-blue-600 text-white shadow-md' 
                              : 'border-gray-100 text-gray-600 bg-gray-50/50 hover:bg-gray-100'
                          }`}
                        >
                          <span className={`text-[10px] uppercase font-bold ${isSelected ? 'text-blue-100' : 'text-gray-400'}`}>
                            {day.dayName}
                          </span>
                          <span className="text-base font-black tracking-tight">{day.num}</span>
                          <span className={`text-[10px] ${isSelected ? 'text-blue-100' : 'text-gray-400'}`}>
                            {day.month}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="block text-xs font-bold text-gray-400 uppercase tracking-wider">Select Time Slot</label>
                  <div className="grid grid-cols-2 gap-2">
                    {slotsAvailable.map((slot) => {
                      const isSelected = selectedSlot === slot;
                      return (
                        <button
                          key={slot}
                          type="button"
                          onClick={() => setSelectedSlot(slot)}
                          className={`p-3 text-xs font-semibold rounded-xl border text-center transition-all ${
                            isSelected 
                              ? 'border-blue-600 bg-blue-50 text-blue-700 font-bold ring-1 ring-blue-600' 
                              : 'border-gray-100 text-gray-600 hover:bg-gray-50'
                          }`}
                        >
                          {slot}
                        </button>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {/* STEP 4: Invoice pre-assessment summary */}
            {step === 4 && (
              <div className="space-y-4" id="step-4-invoice-summary">
                <div className="bg-gray-50 rounded-2xl border border-gray-100 p-4.5 space-y-3">
                  <h4 className="text-xs font-extrabold text-gray-400 uppercase tracking-wider">Summary Receipt</h4>
                  
                  <div className="space-y-2.5 pb-3 border-b border-gray-200">
                    <div className="flex justify-between items-start text-xs text-gray-500">
                      <span>Service Center</span>
                      <span className="font-bold text-gray-800 text-right">{center.name}</span>
                    </div>
                    <div className="flex justify-between text-xs text-gray-500">
                      <span>Ride</span>
                      <span className="font-bold text-gray-800 text-right capitalize">
                        {vehicleType} • <span className="text-xs">{selectedVehicle ? `${selectedVehicle.model}` : 'Standard'}</span>
                      </span>
                    </div>
                    <div className="flex justify-between text-xs text-gray-500">
                      <span>Wash Plan</span>
                      <span className="font-bold text-gray-800 text-right">{selectedService.name}</span>
                    </div>
                    <div className="flex justify-between text-xs text-gray-500">
                      <span>Schedule</span>
                      <span className="font-bold text-gray-800 text-right text-xs">
                        {selectedDate} @ {selectedSlot.split(' ')[0]} {selectedSlot.split(' ')[1]}
                      </span>
                    </div>
                  </div>

                  <div className="space-y-2 text-xs pt-1">
                    <div className="flex justify-between text-gray-400">
                      <span>Base Service Cost</span>
                      <span className="font-semibold text-gray-700">₹{basePrice.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-gray-400">
                      <span>Service Tax (18% GST)</span>
                      <span className="font-semibold text-gray-700">₹{tax.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-sm pt-2 border-t border-dashed border-gray-200 text-gray-800 font-extrabold">
                      <span>Total Invoice Value</span>
                      <span className="text-blue-600 text-base">₹{total.toFixed(2)}</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2.5 text-xs text-gray-400 py-1 font-medium justify-center">
                  <CreditCard className="w-4 h-4 text-gray-400" />
                  <span>Stored signature card / billing index selected</span>
                </div>
              </div>
            )}

            {/* STEP 5: Sparkle Confirmation */}
            {step === 5 && (
              <div className="py-6 flex flex-col items-center text-center space-y-4" id="booking-confirmed-pane">
                <motion.div 
                  initial={{ scale: 0.5, opacity: 0 }}
                  animate={{ scale: [1.2, 1], opacity: 1 }}
                  transition={{ duration: 0.4, type: 'spring' }}
                  className="w-16 h-16 bg-emerald-500 text-white rounded-full flex items-center justify-center shadow-lg"
                >
                  <Check className="w-8 h-8 stroke-[3]" />
                </motion.div>

                <div>
                  <h4 className="text-lg font-black text-gray-900">Appointment Registered!</h4>
                  <p className="text-sm text-gray-500 mt-1 max-w-sm px-4">
                    {isOffline 
                      ? 'Saved securely to your offline outbox store! Your booking and wash slot is guaranteed offline, and sync will happen automatically as soon as internet connection is refreshed.'
                      : 'Your slot is logged instantly on WashDash! Check-in details and automated PDF invoice generation is ready for view under Your Bookings.'}
                  </p>
                </div>

                <div className="w-full bg-slate-50 border border-slate-100 p-3 rounded-xl max-w-xs text-left">
                  <div className="text-[10px] text-slate-400 uppercase font-black tracking-wider">Registration Log</div>
                  <div className="text-xs text-slate-700 font-bold mt-1">Ride: {selectedVehicle ? `${selectedVehicle.model} (${selectedVehicle.paint})` : 'Vehicle'}</div>
                  <div className="text-xs text-slate-700 font-bold">Plan: {selectedService.name}</div>
                  <div className="text-[11px] text-slate-500 mt-0.5">{selectedDate} | {selectedSlot}</div>
                </div>
              </div>
            )}
          </div>

          {/* Footer controls */}
          <div className="p-5 border-t border-gray-100 bg-gray-50 flex gap-3">
            {step < 5 ? (
              <>
                <button
                  type="button"
                  onClick={onClose}
                  className="flex-1 py-3 text-sm font-bold text-gray-500 border border-gray-200 bg-white rounded-2xl hover:bg-gray-50 hover:text-gray-700 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleNext}
                  className="flex-1 py-3 text-sm font-bold text-white bg-blue-600 rounded-2xl hover:bg-blue-700 hover:shadow-lg hover:shadow-blue-200 transition-all flex items-center justify-center gap-1.5"
                >
                  <span>{step === 4 ? 'Confirm & Book' : 'Continue'}</span>
                  <ChevronRight className="w-4 h-4" />
                </button>
              </>
            ) : (
              <button
                type="button"
                onClick={onClose}
                className="w-full py-3 text-sm font-bold text-white bg-slate-900 rounded-2xl hover:bg-slate-800 transition-colors"
              >
                Dismiss Window
              </button>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
